### ISSUE TITLE
Consider rename...

### ISSUE THREAD

**Issue by apeltzer** [nf-core/ddamsproteomics#2]
https://nf-co.re/guidelines#workflow-name

I happened to do the same thing with `rrna-ampliseq` but will rename that one as well. Sorry for not saying this earlier, but please just propose a new name (the shorter the better) and let me know and I can assist here...

**Comment by glormph** [comment]
No problem! You mean to remove the dashes, right?
In that case: ddamsproteomics
I guess quant is implied. Shame though, I liked the dashes!

**Comment by apeltzer** [comment]
Fine by me :-)
